# Generated by Django 3.1.4 on 2020-12-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PressureFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_p', models.FloatField()),
                ('m1', models.FloatField()),
                ('m2', models.FloatField()),
                ('m3', models.FloatField()),
                ('mvmi', models.FloatField()),
                ('deviation', models.FloatField()),
                ('repeat_ability', models.FloatField()),
                ('hysteresis', models.FloatField()),
                ('expand_uncertainity', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.certificate')),
            ],
        ),
    ]
